# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75595e57a4c2fef2ad011c5904fd4c3cb2daf0afafa58461c3715da0562e130f87d36742d0215f469572833da06fe2c073c68d1de4d40162644a8099b3280d7a

test:
  secret_key_base: e31d0043f4a3299b81442f433b8f4f2da61fba74140018e977cd0153a85f418238bd0e3d9264c6859266d6e198d950ed10633a013e0e4dcfa58325fa4a289393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
